export const countryList = [
    { code: "FR", name: "France", locale: "fr_FR"},
    { code: "US", name: "United States of America"},
    { code: "BE", name: "Belgium"},
    { code: "GB", name: "United Kingdom"},
    { code: "CA", name: "Canada"},
    { code: "DE", name: "Germany"},
    { code: "DK", name: "Denmark"},
    { code: "ES", name: "Spain"},
    { code: "IE", name: "Ireland"},
    { code: "IT", name: "Italy"},
    { code: "JP", name: "Japan"},
    { code: "LU", name: "Luxembourg"},
    { code: "NL", name: "Netherlands"},
    { code: "NO", name: "Norway"},
    { code: "PH", name: "Philippines"},
    { code: "SE", name: "Sweden"},
    { code: "AU", name: "Australia"},
    { code: "NZ", name: "New Zealand"},
    { code: "CR", name: "Costa Rica"},
    { code: "CZ", name: "Czech Republic"},
    { code: "FI", name: "Finland"},
    { code: "GR", name: "Greece"},
    { code: "IS", name: "Iceland"},
    { code: "ZA", name: "South Africa"},
    { code: "DO", name: "Dominican Republic"},
    { code: "SV", name: "El Salvador"},
    { code: "HN", name: "Honduras"},
    { code: "MX", name: "Mexico"},
    { code: "NI", name: "Nicaragua"},
    { code: "PA", name: "Panama"},
    { code: "BR", name: "Brazil", locale: "pt-BR"},
    { code: "CL", name: "Chile"},
    { code: "EC", name: "Ecuador"},
    { code: "GT", name: "Guatemala"},
    { code: "BO", name: "Bolivia"}
];
