export const countryList = [
    { code: "DZ", name: "Algeria"},
    { code: "FR", name: "France", locale: "fr_FR"},
    { code: "US", name: "United States of America"},
    { code: "BH", name: "Bahrain"},
    { code: "BE", name: "Belgium"},
    { code: "GB", name: "United Kingdom"},
    { code: "CA", name: "Canada"},
    { code: "DE", name: "Germany"},
    { code: "DK", name: "Denmark"},
    { code: "EG", name: "Egypt"},
    { code: "ES", name: "Spain"},
    { code: "HK", name: "Hong Kong"},
    { code: "IE", name: "Ireland"},
    { code: "IT", name: "Italy"},
    { code: "IN", name: "India"},
    { code: "ID", name: "Indonesia"},
    { code: "IL", name: "Israel"},
    { code: "JO", name: "Jordan"},
    { code: "KW", name: "Kuwait"},
    { code: "LB", name: "Lebanon"},
    { code: "MY", name: "Malaysia"},
    { code: "OM", name: "Oman"},
    { code: "PS", name: "Palestine"},
    { code: "QA", name: "Qatar"},
    { code: "SA", name: "Saudi Arabia"},
    { code: "SG", name: "Singapore"},
    { code: "TW", name: "Taiwan"},
    { code: "TH", name: "Thailand"},
    { code: "AE", name: "United Arab Emirates"},
    { code: "VN", name: "Vietnam"},
    { code: "AD", name: "Andorra"},
    { code: "AT", name: "Austria"},
    { code: "BE", name: "Belgium"},
    { code: "BG", name: "Bulgaria"},
    { code: "CY", name: "Cyprus"},
    { code: "CZ", name: "Czech Republic"},
    { code: "EE", name: "Estonia"},
    { code: "FI", name: "Finland"},
    { code: "GR", name: "Greece"},
    { code: "HU", name: "Hungary"},
    { code: "IS", name: "Iceland"},
    { code: "LV", name: "Latvia"},
    { code: "LI", name: "Liechtenstein"},
    { code: "LT", name: "Lithuania"},
    { code: "MT", name: "Malta"},
    { code: "MC", name: "Monaco"},
    { code: "PL", name: "Poland"},
    { code: "PT", name: "Portugal"},
    { code: "RO", name: "Romania"},
    { code: "SK", name: "Slovakia"},
    { code: "CH", name: "Switzerland"},
    { code: "TR", name: "Turkey"},
    { code: "RU", name: "Russia"},
    { code: "BY", name: "Belarus"},
    { code: "KZ", name: "Kazakhstan"},
    { code: "MD", name: "Moldova"},
    { code: "UA", name: "Ukraine"},
    { code: "AL", name: "Albania"},
    { code: "BA", name: "Bosnia"},
    { code: "HR", name: "Croatia"},
    { code: "ME", name: "Montenegro"},
    { code: "MK", name: "North Macedonia"},
    { code: "RS", name: "Serbia"},
    { code: "SI", name: "Slovenia"},
    { code: "RS", name: "Kosovo"},
    { code: "CR", name: "Costa Rica"},
    { code: "DO", name: "Dominican Republic"},
    { code: "SV", name: "El Salvador"},
    { code: "HN", name: "Honduras"},
    { code: "MX", name: "Mexico"},
    { code: "NI", name: "Nicaragua"},
    { code: "PA", name: "Panama"},
    { code: "AR", name: "Argentina"},
    { code: "CO", name: "Colombia"},
    { code: "PY", name: "Paraguay"},
    { code: "PE", name: "Peru"},
    { code: "UY", name: "Uruguay"},
    { code: "AU", name: "Australia"},
    { code: "NZ", name: "New Zealand"},
    { code: "JP", name: "Japan"},
    { code: "LU", name: "Luxembourg"},
    { code: "MA", name: "Morocco"},
    { code: "NL", name: "Netherlands"},
    { code: "NO", name: "Norway"},
    { code: "PH", name: "Philippines"},
    { code: "SE", name: "Sweden"},
    { code: "ZA", name: "South Africa"},
    { code: "TN", name: "Tunisia"},
    { code: "BR", name: "Brazil", locale: "pt-BR"},
    { code: "CL", name: "Chile"},
    { code: "EC", name: "Ecuador"},
    { code: "GT", name: "Guatemala"},
    { code: "BO", name: "Bolivia"},
  
];
