import { CountryListElement } from '../dtos/country-list';

export const countryList: CountryListElement[] = [
    { code: 'FR', name: 'France', locale: 'fr_FR', isPrimary: false},
    { code: 'US', name: 'United States of America', isPrimary: false},
    { code: 'BE', name: 'Belgium', isPrimary: false},
    { code: 'GB', name: 'United Kingdom', isPrimary: false},
    { code: 'CA', name: 'Canada', isPrimary: false},
    { code: 'DE', name: 'Germany', isPrimary: false},
    { code: 'DK', name: 'Denmark', isPrimary: false},
    { code: 'ES', name: 'Spain', isPrimary: false},
    { code: 'IE', name: 'Ireland', isPrimary: false},
    { code: 'IT', name: 'Italy', isPrimary: false},
    { code: 'JP', name: 'Japan', isPrimary: false},
    { code: 'LU', name: 'Luxembourg', isPrimary: false},
    { code: 'NL', name: 'Netherlands', isPrimary: false},
    { code: 'NO', name: 'Norway', isPrimary: false},
    { code: 'PH', name: 'Philippines', isPrimary: false},
    { code: 'SE', name: 'Sweden', isPrimary: false},
    { code: 'AU', name: 'Australia', isPrimary: false},
    { code: 'NZ', name: 'New Zealand', isPrimary: false},
    { code: 'CR', name: 'Costa Rica', isPrimary: false},
    { code: 'CZ', name: 'Czech Republic', isPrimary: false},
    { code: 'FI', name: 'Finland', isPrimary: false},
    { code: 'GR', name: 'Greece', isPrimary: false},
    { code: 'IS', name: 'Iceland', isPrimary: false},
    { code: 'ZA', name: 'South Africa', isPrimary: false},
    { code: 'DO', name: 'Dominican Republic', isPrimary: false},
    { code: 'SV', name: 'El Salvador', isPrimary: false},
    { code: 'HN', name: 'Honduras', isPrimary: false},
    { code: 'MX', name: 'Mexico', isPrimary: false},
    { code: 'NI', name: 'Nicaragua', isPrimary: false},
    { code: 'PA', name: 'Panama', isPrimary: false},
    { code: 'BR', name: 'Brazil', locale: 'pt-BR', isPrimary: false},
    { code: 'CL', name: 'Chile', isPrimary: false},
    { code: 'EC', name: 'Ecuador', isPrimary: false},
    { code: 'GT', name: 'Guatemala', isPrimary: false},
    { code: 'BO', name: 'Bolivia', isPrimary: false}
];
